package io.legado.app.ui.book.manga

import androidx.compose.runtime.Immutable
import io.legado.app.data.entities.Book

@Immutable
data class MangaBookSnapshot(
    val bookUrl: String,
    val tocUrl: String,
    val origin: String,
    val originName: String,
    val name: String,
    val author: String,
    val kind: String?,
    val customTag: String?,
    val coverUrl: String?,
    val customCoverUrl: String?,
    val intro: String?,
    val customIntro: String?,
    val remark: String?,
    val charset: String?,
    val type: Int,
    val group: Long,
    val latestChapterTitle: String?,
    val latestChapterTime: Long,
    val lastCheckTime: Long,
    val lastCheckCount: Int,
    val totalChapterNum: Int,
    val durChapterTitle: String?,
    val durChapterIndex: Int,
    val durChapterPos: Int,
    val durChapterTime: Long,
    val wordCount: String?,
    val canUpdate: Boolean,
    val order: Int,
    val originOrder: Int,
    val variable: String?,
    val readConfig: MangaReadConfigSnapshot?,
    val syncTime: Long,
    val listIntro: String?,
) {
    fun toBook() = Book(
        bookUrl = bookUrl,
        tocUrl = tocUrl,
        origin = origin,
        originName = originName,
        name = name,
        author = author,
        kind = kind,
        customTag = customTag,
        coverUrl = coverUrl,
        customCoverUrl = customCoverUrl,
        intro = intro,
        customIntro = customIntro,
        remark = remark,
        charset = charset,
        type = type,
        group = group,
        latestChapterTitle = latestChapterTitle,
        latestChapterTime = latestChapterTime,
        lastCheckTime = lastCheckTime,
        lastCheckCount = lastCheckCount,
        totalChapterNum = totalChapterNum,
        durChapterTitle = durChapterTitle,
        durChapterIndex = durChapterIndex,
        durChapterPos = durChapterPos,
        durChapterTime = durChapterTime,
        wordCount = wordCount,
        canUpdate = canUpdate,
        order = order,
        originOrder = originOrder,
        variable = variable,
        readConfig = readConfig?.toReadConfig(),
        syncTime = syncTime,
        listIntro = listIntro,
    )

    companion object {
        fun from(book: Book) = MangaBookSnapshot(
            bookUrl = book.bookUrl,
            tocUrl = book.tocUrl,
            origin = book.origin,
            originName = book.originName,
            name = book.name,
            author = book.author,
            kind = book.kind,
            customTag = book.customTag,
            coverUrl = book.coverUrl,
            customCoverUrl = book.customCoverUrl,
            intro = book.intro,
            customIntro = book.customIntro,
            remark = book.remark,
            charset = book.charset,
            type = book.type,
            group = book.group,
            latestChapterTitle = book.latestChapterTitle,
            latestChapterTime = book.latestChapterTime,
            lastCheckTime = book.lastCheckTime,
            lastCheckCount = book.lastCheckCount,
            totalChapterNum = book.totalChapterNum,
            durChapterTitle = book.durChapterTitle,
            durChapterIndex = book.durChapterIndex,
            durChapterPos = book.durChapterPos,
            durChapterTime = book.durChapterTime,
            wordCount = book.wordCount,
            canUpdate = book.canUpdate,
            order = book.order,
            originOrder = book.originOrder,
            variable = book.variable,
            readConfig = book.readConfig?.let(MangaReadConfigSnapshot::from),
            syncTime = book.syncTime,
            listIntro = book.listIntro,
        )
    }
}

@Immutable
data class MangaReadConfigSnapshot(
    val reverseToc: Boolean,
    val pageAnim: Int?,
    val reSegment: Boolean,
    val imageStyle: String?,
    val useReplaceRule: Boolean?,
    val delTag: Long,
    val ttsEngine: String?,
    val splitLongChapter: Boolean,
    val readSimulating: Boolean,
    val startDate: String?,
    val startChapter: Int?,
    val dailyChapters: Int,
    val mangaColorFilter: String?,
    val mangaScrollMode: Int?,
    val webtoonSidePaddingDp: Int?,
    val mangaBackground: String?,
    val fixedType: Boolean,
    val translationMode: Boolean,
) {
    fun toReadConfig() = Book.ReadConfig(
        reverseToc = reverseToc,
        pageAnim = pageAnim,
        reSegment = reSegment,
        imageStyle = imageStyle,
        useReplaceRule = useReplaceRule,
        delTag = delTag,
        ttsEngine = ttsEngine,
        splitLongChapter = splitLongChapter,
        readSimulating = readSimulating,
        startDate = startDate,
        startChapter = startChapter,
        dailyChapters = dailyChapters,
        mangaColorFilter = mangaColorFilter,
        mangaScrollMode = mangaScrollMode,
        webtoonSidePaddingDp = webtoonSidePaddingDp,
        mangaBackground = mangaBackground,
        fixedType = fixedType,
        translationMode = translationMode,
    )

    companion object {
        fun from(config: Book.ReadConfig) = MangaReadConfigSnapshot(
            reverseToc = config.reverseToc,
            pageAnim = config.pageAnim,
            reSegment = config.reSegment,
            imageStyle = config.imageStyle,
            useReplaceRule = config.useReplaceRule,
            delTag = config.delTag,
            ttsEngine = config.ttsEngine,
            splitLongChapter = config.splitLongChapter,
            readSimulating = config.readSimulating,
            startDate = config.startDate,
            startChapter = config.startChapter,
            dailyChapters = config.dailyChapters,
            mangaColorFilter = config.mangaColorFilter,
            mangaScrollMode = config.mangaScrollMode,
            webtoonSidePaddingDp = config.webtoonSidePaddingDp,
            mangaBackground = config.mangaBackground,
            fixedType = config.fixedType,
            translationMode = config.translationMode,
        )
    }
}
