package io.legado.app.domain.model.settings

import io.legado.app.data.entities.BookGroup

data class BookshelfSettings(
    val bookGroupStyle: Int = 0,
    val hideEmptyGroups: Boolean = true,
    val bookshelfSort: Int = 0,
    val bookshelfSortOrder: Int = 1,
    val showUnread: Boolean = true,
    val showUnreadNew: Boolean = true,
    val showTip: Boolean = false,
    val showBookCount: Boolean = true,
    val showLastUpdateTime: Boolean = false,
    val showBookIntro: Boolean = false,
    val bookshelfShowIntro: Boolean = true,
    val bookshelfShowTag: Boolean = true,
    val bookshelfShowLatestChapter: Boolean = true,
    val bookshelfIntroMaxLines: Int = 0,
    val showWaitUpCount: Boolean = false,
    val showBookshelfFastScroller: Boolean = false,
    val shouldShowExpandButton: Boolean = false,
    val bookshelfRefreshingLimit: Int = 0,
    val bookshelfLayoutModePortrait: Int = 1,
    val bookshelfLayoutGridPortrait: Int = 3,
    val bookshelfLayoutModeLandscape: Int = 1,
    val bookshelfLayoutGridLandscape: Int = 7,
    val bookshelfLayoutListPortrait: Int = 1,
    val bookshelfLayoutListLandscape: Int = 1,
    val bookshelfFolderLayoutModePortrait: Int = 1,
    val bookshelfFolderLayoutGridPortrait: Int = 3,
    val bookshelfFolderLayoutModeLandscape: Int = 1,
    val bookshelfFolderLayoutGridLandscape: Int = 7,
    val bookshelfFolderLayoutListPortrait: Int = 1,
    val bookshelfFolderLayoutListLandscape: Int = 1,
    val bookshelfGridLayout: Int = 0,
    val bookshelfLayoutCompact: Boolean = false,
    val bookshelfListCoverCenter: Boolean = true,
    val bookshelfListIntroBelowContent: Boolean = false,
    val bookshelfShowDivider: Boolean = true,
    val bookshelfTitleSmallFont: Boolean = false,
    val bookshelfTitleCenter: Boolean = true,
    val bookshelfTitleMaxLines: Int = 2,
    val bookshelfCoverShadow: Boolean = false,
    val bookshelfCardColor: Int = 0,
    val bookshelfCardColorDark: Int = 0,
    val bookshelfGroupListStyle: Int = 0,
    val bookshelfGroupCoverCount: Int = 4,
    val bookshelfListCoverWidth: Int = 84,
    val bookshelfGridCoverWidth: Int = 120,
    val bookshelfSearchActionDirectToSearch: Boolean = true,
    val autoRefreshBook: Boolean = false,
    val saveTabPosition: Long = BookGroup.IdAll,
)
